cellsociety_team01: cellsociety_team01.simulations.GameOfLife Class Reference
cellsociety_team01.simulations.GameOfLife Class Reference
Public Member Functions
GameOfLife ()
void initialize ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
int getNeighborType ()
Public Member Functions inherited from cellsociety_team01.simulations.Simulation
Simulation ()
int getNumPossibleStates ()
int getNeighborType ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
void setUpdated (Cell c)
State findState (String identifier)
Set< State > getStates ()
void setConfigs (Map< String, String > a)
void initialize ()
void parseConfigs (Map< String, String > a)
State cycleNextState (State s)
Additional Inherited Members
Protected Attributes inherited from cellsociety_team01.simulations.Simulation
Map< State, ArrayList< Rule > > myData
ResourceBundle myColorScheme
Detailed Description
Definition at line 13 of file GameOfLife.java.
Constructor & Destructor Documentation
cellsociety_team01.simulations.GameOfLife.GameOfLife ()
Definition at line 15 of file GameOfLife.java.
Member Function Documentation
int cellsociety_team01.simulations.GameOfLife.getNeighborType ()
Definition at line 41 of file GameOfLife.java.
void cellsociety_team01.simulations.GameOfLife.initialize ()
Definition at line 20 of file GameOfLife.java.
References cellsociety_team01.simulations.Simulation.myColorScheme, and cellsociety_team01.simulations.Simulation.myData.
void cellsociety_team01.simulations.GameOfLife.update (Cell cur, ArrayList< Cell > myNeighbors)
Definition at line 33 of file GameOfLife.java.
References cellsociety_team01.CellState.Cell.getCurState(), cellsociety_team01.CellState.Cell.isUpdated(), cellsociety_team01.simulations.Simulation.myData, and cellsociety_team01.CellState.Cell.setNextState().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/simulations/GameOfLife.java