cellsociety_team01: cellsociety_team01.rules.MovementRule Class Reference
cellsociety_team01.rules.MovementRule Class Reference
Public Member Functions
MovementRule (State targetState)
void update ()
void apply (Cell cur, ArrayList< Cell > myNeighbors)
Cell pickCell (State target, ArrayList< Cell > myNeighbors)
void switchStatesUpdated (Cell a, Cell b, boolean aUpdated, boolean bUpdated)
Public Member Functions inherited from cellsociety_team01.rules.Rule
Rule ()
void update ()
void apply (Cell cur, ArrayList< Cell > myNeighbors)
Protected Attributes
State myTargetState
Private Attributes
Random myRandom = new Random()
Detailed Description
Definition at line 11 of file MovementRule.java.
Constructor & Destructor Documentation
cellsociety_team01.rules.MovementRule.MovementRule (State targetState)
Definition at line 16 of file MovementRule.java.
Member Function Documentation
void cellsociety_team01.rules.MovementRule.apply (Cell cur, ArrayList< Cell > myNeighbors)
Definition at line 22 of file MovementRule.java.
References cellsociety_team01.CellState.Cell.getCurState(), cellsociety_team01.CellState.Cell.isUpdated(), cellsociety_team01.rules.MovementRule.pickCell(), cellsociety_team01.CellState.Cell.setCurState(), cellsociety_team01.CellState.Cell.setNextState(), and cellsociety_team01.CellState.Cell.setUpdated().
Cell cellsociety_team01.rules.MovementRule.pickCell (State target, ArrayList< Cell > myNeighbors)
Definition at line 44 of file MovementRule.java.
Referenced by cellsociety_team01.rules.ThresholdMovementRule.apply(), cellsociety_team01.rules.MovementRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), and cellsociety_team01.rules.ConsumptionRule.apply().
void cellsociety_team01.rules.MovementRule.switchStatesUpdated (Cell a, Cell b, boolean aUpdated, boolean bUpdated)
Definition at line 61 of file MovementRule.java.
References cellsociety_team01.CellState.Cell.getCurState(), cellsociety_team01.CellState.Cell.setCurState(), cellsociety_team01.CellState.Cell.setNextState(), and cellsociety_team01.CellState.Cell.setUpdated().
Referenced by cellsociety_team01.rules.ThresholdMovementRule.apply(), and cellsociety_team01.rules.ConsumptionRule.eat().
void cellsociety_team01.rules.MovementRule.update ()
Definition at line 20 of file MovementRule.java.
Member Data Documentation
Random cellsociety_team01.rules.MovementRule.myRandom = new Random() private
Definition at line 13 of file MovementRule.java.
State cellsociety_team01.rules.MovementRule.myTargetState protected
Definition at line 14 of file MovementRule.java.
Referenced by cellsociety_team01.rules.ThresholdMovementRule.apply(), cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.PriorityForwardRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.rules.ConsumptionRule.apply(), and cellsociety_team01.rules.UphillMovementRule.pickCell().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/rules/MovementRule.java