cellsociety_team01: cellsociety_team01.CellState.State Class Reference
cellsociety_team01.CellState.State Class Reference
Public Member Functions
State (Color c, String s)
State newInstanceOf ()
boolean equals (Object s)
int hashCode ()
void setColor (Color color)
void setName (String s)
String getName ()
Color getColor ()
int getInt (int a)
int getNumArgs ()
void setInt (int a, int b)
boolean comparePopulations (State curState)
String getDemonym ()
void updateColor ()
boolean getFunc ()
Protected Attributes
Color myColor
String myName
Detailed Description
Definition at line 5 of file State.java.
Constructor & Destructor Documentation
cellsociety_team01.CellState.State.State (Color c, String s)
Definition at line 9 of file State.java.
Referenced by cellsociety_team01.CellState.State.equals(), and cellsociety_team01.CellState.State.newInstanceOf().
Member Function Documentation
boolean cellsociety_team01.CellState.State.comparePopulations (State curState)
Definition at line 66 of file State.java.
References cellsociety_team01.CellState.State.equals(), and cellsociety_team01.CellState.State.getName().
boolean cellsociety_team01.CellState.State.equals (Object s)
Definition at line 20 of file State.java.
References cellsociety_team01.CellState.State.getName(), and cellsociety_team01.CellState.State.State().
Referenced by cellsociety_team01.CellState.State.comparePopulations().
Color cellsociety_team01.CellState.State.getColor ()
Definition at line 48 of file State.java.
References cellsociety_team01.CellState.State.myColor.
String cellsociety_team01.CellState.State.getDemonym ()
Definition at line 71 of file State.java.
boolean cellsociety_team01.CellState.State.getFunc ()
Definition at line 79 of file State.java.
Referenced by cellsociety_team01.rules.PriorityForwardRule.apply().
int cellsociety_team01.CellState.State.getInt (int a)
Definition at line 53 of file State.java.
Referenced by cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.StatusRule.apply(), cellsociety_team01.rules.ThresholdStatusRule.apply(), cellsociety_team01.rules.PriorityForwardRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.rules.ConsumptionRule.apply(), and cellsociety_team01.rules.UphillMovementRule.pickCell().
String cellsociety_team01.CellState.State.getName ()
Definition at line 44 of file State.java.
References cellsociety_team01.CellState.State.myName.
Referenced by cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.CellState.State.comparePopulations(), and cellsociety_team01.CellState.State.equals().
int cellsociety_team01.CellState.State.getNumArgs ()
Definition at line 57 of file State.java.
int cellsociety_team01.CellState.State.hashCode ()
Definition at line 27 of file State.java.
State cellsociety_team01.CellState.State.newInstanceOf ()
Definition at line 14 of file State.java.
References cellsociety_team01.CellState.State.State().
Referenced by cellsociety_team01.rules.ReproductionRule.apply(), and cellsociety_team01.simulations.Simulation.findState().
void cellsociety_team01.CellState.State.setColor (Color color)
Definition at line 36 of file State.java.
void cellsociety_team01.CellState.State.setInt (int a, int b)
Definition at line 61 of file State.java.
Referenced by cellsociety_team01.rules.averageUpdateRule.apply(), cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.StatusRule.apply(), cellsociety_team01.rules.ThresholdStatusRule.apply(), cellsociety_team01.rules.PriorityForwardRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.rules.ConsumptionRule.apply(), cellsociety_team01.rules.ConsumptionRule.eat(), cellsociety_team01.simulations.SlimeMolds.initialize(), and cellsociety_team01.simulations.AntForaging.initialize().
void cellsociety_team01.CellState.State.setName (String s)
Definition at line 40 of file State.java.
void cellsociety_team01.CellState.State.updateColor ()
Definition at line 75 of file State.java.
Referenced by cellsociety_team01.simulations.SlimeMolds.update(), and cellsociety_team01.simulations.Sugarscape.update().
Member Data Documentation
Color cellsociety_team01.CellState.State.myColor protected
Definition at line 6 of file State.java.
Referenced by cellsociety_team01.CellState.State.getColor(), cellsociety_team01.CellState.IntState.newInstanceOf(), cellsociety_team01.CellState.ColorChangeIntState.newInstanceOf(), and cellsociety_team01.CellState.ColorChangeIntState.updateColor().
String cellsociety_team01.CellState.State.myName protected
Definition at line 7 of file State.java.
Referenced by cellsociety_team01.CellState.State.getName(), cellsociety_team01.CellState.IntState.newInstanceOf(), and cellsociety_team01.CellState.ColorChangeIntState.newInstanceOf().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/CellState/State.java