cellsociety_team01: cellsociety_team01.rules.ConsumptionRule Class Reference
cellsociety_team01.rules.ConsumptionRule Class Reference
Public Member Functions
ConsumptionRule (State targetCellType, State emptyCellType, double t, int dataIndex)
void kill (Cell cur, State target)
void apply (Cell cur, ArrayList< Cell > myNeighbors)
Public Member Functions inherited from cellsociety_team01.rules.MovementRule
MovementRule (State targetState)
void update ()
void apply (Cell cur, ArrayList< Cell > myNeighbors)
Cell pickCell (State target, ArrayList< Cell > myNeighbors)
void switchStatesUpdated (Cell a, Cell b, boolean aUpdated, boolean bUpdated)
Public Member Functions inherited from cellsociety_team01.rules.Rule
Rule ()
void update ()
void apply (Cell cur, ArrayList< Cell > myNeighbors)
Private Member Functions
void eat (Cell prey, Cell predator)
Private Attributes
State myEmpty
double myTurnsThreshold
int myDataIndex
Additional Inherited Members
Protected Attributes inherited from cellsociety_team01.rules.MovementRule
State myTargetState
Detailed Description
Definition at line 7 of file ConsumptionRule.java.
Constructor & Destructor Documentation
cellsociety_team01.rules.ConsumptionRule.ConsumptionRule (State targetCellType, State emptyCellType, double t, int dataIndex)
Definition at line 13 of file ConsumptionRule.java.
Member Function Documentation
void cellsociety_team01.rules.ConsumptionRule.apply (Cell cur, ArrayList< Cell > myNeighbors)
Definition at line 28 of file ConsumptionRule.java.
References cellsociety_team01.rules.ConsumptionRule.eat(), cellsociety_team01.CellState.Cell.getCurState(), cellsociety_team01.CellState.State.getInt(), cellsociety_team01.rules.ConsumptionRule.kill(), cellsociety_team01.rules.MovementRule.myTargetState, cellsociety_team01.rules.ConsumptionRule.myTurnsThreshold, cellsociety_team01.rules.MovementRule.pickCell(), and cellsociety_team01.CellState.State.setInt().
void cellsociety_team01.rules.ConsumptionRule.eat (Cell prey, Cell predator) private
Definition at line 48 of file ConsumptionRule.java.
References cellsociety_team01.CellState.Cell.getNextState(), cellsociety_team01.CellState.Cell.setCurState(), cellsociety_team01.CellState.State.setInt(), and cellsociety_team01.rules.MovementRule.switchStatesUpdated().
Referenced by cellsociety_team01.rules.ConsumptionRule.apply().
void cellsociety_team01.rules.ConsumptionRule.kill (Cell cur, State target)
Definition at line 21 of file ConsumptionRule.java.
References cellsociety_team01.CellState.Cell.setCurState(), and cellsociety_team01.CellState.Cell.setNextState().
Referenced by cellsociety_team01.rules.ConsumptionRule.apply().
Member Data Documentation
int cellsociety_team01.rules.ConsumptionRule.myDataIndex private
Definition at line 11 of file ConsumptionRule.java.
State cellsociety_team01.rules.ConsumptionRule.myEmpty private
Definition at line 9 of file ConsumptionRule.java.
double cellsociety_team01.rules.ConsumptionRule.myTurnsThreshold private
Definition at line 10 of file ConsumptionRule.java.
Referenced by cellsociety_team01.rules.ConsumptionRule.apply().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/rules/ConsumptionRule.java