cellsociety_team01: cellsociety_team01.modelview.GridModel Class Reference
cellsociety_team01.modelview.GridModel Class Reference abstract
Public Member Functions
GridModel (gridEdgeTypes myEdgeTypeIn)
void setNeighbors (Map< Pair, Cell > cellMap, Simulation simulation, int rows, int cols)
Protected Member Functions
abstract ArrayList< Pair > getCardinalNeighbors (Cell cell, int levels)
ArrayList< Pair > getAllPossibleNeighbors (Cell cell, int levels)
ArrayList< Cell > verifyNeighbors (Map< Pair, Cell > cellMap, int rows, int cols, Pair pair, ArrayList< Pair > possibleNeighbors)
Private Attributes
RefineNeighborsAlgorithm[] rna
RefineNeighborsAlgorithm myRefineAlgorithm
Detailed Description
Definition at line 15 of file GridModel.java.
Constructor & Destructor Documentation
cellsociety_team01.modelview.GridModel.GridModel (gridEdgeTypes myEdgeTypeIn)
Definition at line 22 of file GridModel.java.
References cellsociety_team01.modelview.Grid.gridEdgeTypes.FINITE, and cellsociety_team01.modelview.Grid.gridEdgeTypes.INFINITE.
Member Function Documentation
ArrayList<Pair> cellsociety_team01.modelview.GridModel.getAllPossibleNeighbors (Cell cell, int levels) protected
Abstract Method that returns an array of neighbors in all directions from the cell, levels steps away from the cell
Parameters
cell
levels
Returns
Definition at line 51 of file GridModel.java.
References cellsociety_team01.CellState.Cell.getX(), and cellsociety_team01.CellState.Cell.getY().
Referenced by cellsociety_team01.modelview.GridModel.setNeighbors().
abstract ArrayList<Pair> cellsociety_team01.modelview.GridModel.getCardinalNeighbors (Cell cell, int levels) abstract protected
Abstract Method that returns an array of neighbors in the cardinal directions from the cell, levels steps away from the cell
Parameters
cell
levels
Returns
Referenced by cellsociety_team01.modelview.GridModel.setNeighbors().
void cellsociety_team01.modelview.GridModel.setNeighbors (Map< Pair, Cell > cellMap, Simulation simulation, int rows, int cols)
Finds the finite set neighbors of each cell
Parameters
cellMap
simulation
rows
cols
Definition at line 74 of file GridModel.java.
References cellsociety_team01.modelview.GridModel.getAllPossibleNeighbors(), cellsociety_team01.modelview.GridModel.getCardinalNeighbors(), cellsociety_team01.simulations.Simulation.getNeighborType(), and cellsociety_team01.modelview.GridModel.verifyNeighbors().
Referenced by cellsociety_team01.modelview.Grid.setNeighbors().
ArrayList<Cell> cellsociety_team01.modelview.GridModel.verifyNeighbors (Map< Pair, Cell > cellMap, int rows, int cols, Pair pair, ArrayList< Pair > possibleNeighbors) protected
Checks the array of neighbors for legality, this will be overridden by subclasses
Parameters
cellMap
rows
cols
pair
possibleNeighbors
Returns
Definition at line 112 of file GridModel.java.
References cellsociety_team01.modelview.RefineNeighborsAlgorithm.refineNeighbors().
Referenced by cellsociety_team01.modelview.GridModel.setNeighbors().
Member Data Documentation
RefineNeighborsAlgorithm cellsociety_team01.modelview.GridModel.myRefineAlgorithm private
Definition at line 20 of file GridModel.java.
RefineNeighborsAlgorithm [] cellsociety_team01.modelview.GridModel.rna private
Initial value:
= {
            new FiniteRefineNeighborsAlgorithm(),
            new InfiniteRefineNeighborsAlgorithm(),
            new ToroidalRefineNeighborsAlgorithm() }
Definition at line 16 of file GridModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/modelview/GridModel.java