cellsociety_team01: cellsociety_team01.CellState.ColorChangeIntState Class Reference
cellsociety_team01.CellState.ColorChangeIntState Class Reference
Public Member Functions
ColorChangeIntState (Color myColor, String s, int i, Color baselineColor, int colorStatusIndex, int colorStatusBaseline)
void updateColor ()
State newInstanceOf ()
Public Member Functions inherited from cellsociety_team01.CellState.IntState
IntState (Color c, String s, int i)
State newInstanceOf ()
void initialize ()
boolean equals (State s)
int hashCode ()
int getNumVars ()
int[] getStateNums ()
int getInt (int i)
void setInt (int target, int value)
Public Member Functions inherited from cellsociety_team01.CellState.State
State (Color c, String s)
State newInstanceOf ()
boolean equals (Object s)
int hashCode ()
void setColor (Color color)
void setName (String s)
String getName ()
Color getColor ()
int getInt (int a)
int getNumArgs ()
void setInt (int a, int b)
boolean comparePopulations (State curState)
String getDemonym ()
void updateColor ()
boolean getFunc ()
Private Attributes
int myColorStatusIndex
int myColorStatusBaseline
Random myRandom = new Random()
Color myBaselineColor
Additional Inherited Members
Protected Attributes inherited from cellsociety_team01.CellState.IntState
int[] stateNums
Protected Attributes inherited from cellsociety_team01.CellState.State
Color myColor
String myName
Detailed Description
Definition at line 7 of file ColorChangeIntState.java.
Constructor & Destructor Documentation
cellsociety_team01.CellState.ColorChangeIntState.ColorChangeIntState (Color myColor, String s, int i, Color baselineColor, int colorStatusIndex, int colorStatusBaseline)
Definition at line 14 of file ColorChangeIntState.java.
Referenced by cellsociety_team01.CellState.ColorChangeIntState.newInstanceOf().
Member Function Documentation
State cellsociety_team01.CellState.ColorChangeIntState.newInstanceOf ()
Definition at line 33 of file ColorChangeIntState.java.
References cellsociety_team01.CellState.ColorChangeIntState.ColorChangeIntState(), cellsociety_team01.CellState.State.myColor, cellsociety_team01.CellState.State.myName, cellsociety_team01.CellState.IntState.setInt(), and cellsociety_team01.CellState.IntState.stateNums.
void cellsociety_team01.CellState.ColorChangeIntState.updateColor ()
Definition at line 21 of file ColorChangeIntState.java.
References cellsociety_team01.CellState.ColorChangeIntState.myBaselineColor, cellsociety_team01.CellState.State.myColor, cellsociety_team01.CellState.ColorChangeIntState.myColorStatusBaseline, cellsociety_team01.CellState.ColorChangeIntState.myColorStatusIndex, and cellsociety_team01.CellState.IntState.stateNums.
Member Data Documentation
Color cellsociety_team01.CellState.ColorChangeIntState.myBaselineColor private
Definition at line 12 of file ColorChangeIntState.java.
Referenced by cellsociety_team01.CellState.ColorChangeIntState.updateColor().
int cellsociety_team01.CellState.ColorChangeIntState.myColorStatusBaseline private
Definition at line 10 of file ColorChangeIntState.java.
Referenced by cellsociety_team01.CellState.ColorChangeIntState.updateColor().
int cellsociety_team01.CellState.ColorChangeIntState.myColorStatusIndex private
Definition at line 9 of file ColorChangeIntState.java.
Referenced by cellsociety_team01.CellState.ColorChangeIntState.updateColor().
Random cellsociety_team01.CellState.ColorChangeIntState.myRandom = new Random() private
Definition at line 11 of file ColorChangeIntState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/CellState/ColorChangeIntState.java