cellsociety_team01: cellsociety_team01.simulations.SlimeMolds Class Reference
cellsociety_team01.simulations.SlimeMolds Class Reference
Public Member Functions
SlimeMolds ()
void initialize ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
void parseConfigs (Map< String, String > configs)
Public Member Functions inherited from cellsociety_team01.simulations.Simulation
Simulation ()
int getNumPossibleStates ()
int getNeighborType ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
void setUpdated (Cell c)
State findState (String identifier)
Set< State > getStates ()
void setConfigs (Map< String, String > a)
void initialize ()
void parseConfigs (Map< String, String > a)
State cycleNextState (State s)
Private Attributes
int myMaxPheremone
Additional Inherited Members
Protected Attributes inherited from cellsociety_team01.simulations.Simulation
Map< State, ArrayList< Rule > > myData
ResourceBundle myColorScheme
Detailed Description
Definition at line 14 of file SlimeMolds.java.
Constructor & Destructor Documentation
cellsociety_team01.simulations.SlimeMolds.SlimeMolds ()
Definition at line 18 of file SlimeMolds.java.
Member Function Documentation
void cellsociety_team01.simulations.SlimeMolds.initialize ()
Definition at line 23 of file SlimeMolds.java.
References cellsociety_team01.simulations.Simulation.myColorScheme, cellsociety_team01.simulations.Simulation.myData, and cellsociety_team01.CellState.State.setInt().
void cellsociety_team01.simulations.SlimeMolds.parseConfigs (Map< String, String > configs)
Definition at line 45 of file SlimeMolds.java.
void cellsociety_team01.simulations.SlimeMolds.update (Cell cur, ArrayList< Cell > myNeighbors)
Definition at line 37 of file SlimeMolds.java.
References cellsociety_team01.CellState.Cell.getCurState(), cellsociety_team01.simulations.Simulation.myData, and cellsociety_team01.CellState.State.updateColor().
Member Data Documentation
int cellsociety_team01.simulations.SlimeMolds.myMaxPheremone private
Definition at line 16 of file SlimeMolds.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/simulations/SlimeMolds.java