cellsociety_team01: cellsociety_team01.simulations.Simulation Class Reference
cellsociety_team01.simulations.Simulation Class Reference
Public Member Functions
Simulation ()
int getNumPossibleStates ()
int getNeighborType ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
void setUpdated (Cell c)
State findState (String identifier)
Set< State > getStates ()
void setConfigs (Map< String, String > a)
void initialize ()
void parseConfigs (Map< String, String > a)
State cycleNextState (State s)
Protected Attributes
Map< State, ArrayList< Rule > > myData
ResourceBundle myColorScheme
Static Private Attributes
static final String COLORSCHEME_RESOURCE_PACKAGE = "resources/ColorScheme/ColorScheme"
Detailed Description
Definition at line 16 of file Simulation.java.
Constructor & Destructor Documentation
cellsociety_team01.simulations.Simulation.Simulation ()
Definition at line 22 of file Simulation.java.
Member Function Documentation
State cellsociety_team01.simulations.Simulation.cycleNextState (State s)
Definition at line 74 of file Simulation.java.
Referenced by cellsociety_team01.modelview.Grid.cycleCellState().
State cellsociety_team01.simulations.Simulation.findState (String identifier)
Definition at line 44 of file Simulation.java.
References cellsociety_team01.exceptions.BadStateException.handleException(), and cellsociety_team01.CellState.State.newInstanceOf().
Referenced by cellsociety_team01.parser.Parser.getState().
int cellsociety_team01.simulations.Simulation.getNeighborType ()
Definition at line 33 of file Simulation.java.
Referenced by cellsociety_team01.modelview.GridModel.setNeighbors().
int cellsociety_team01.simulations.Simulation.getNumPossibleStates ()
Definition at line 26 of file Simulation.java.
Referenced by cellsociety_team01.parser.Parser.parseGrid().
Set<State> cellsociety_team01.simulations.Simulation.getStates ()
Definition at line 57 of file Simulation.java.
Referenced by cellsociety_team01.modelview.Grid.updateCells().
void cellsociety_team01.simulations.Simulation.initialize ()
Definition at line 68 of file Simulation.java.
Referenced by cellsociety_team01.simulations.Simulation.setConfigs().
void cellsociety_team01.simulations.Simulation.parseConfigs (Map< String, String > a)
Definition at line 70 of file Simulation.java.
Referenced by cellsociety_team01.simulations.Simulation.setConfigs().
void cellsociety_team01.simulations.Simulation.setConfigs (Map< String, String > a)
Definition at line 61 of file Simulation.java.
References cellsociety_team01.simulations.Simulation.initialize(), and cellsociety_team01.simulations.Simulation.parseConfigs().
Referenced by cellsociety_team01.parser.Parser.parseConfig().
void cellsociety_team01.simulations.Simulation.setUpdated (Cell c)
Definition at line 39 of file Simulation.java.
References cellsociety_team01.CellState.Cell.setUpdated().
void cellsociety_team01.simulations.Simulation.update (Cell cur, ArrayList< Cell > myNeighbors)
Definition at line 35 of file Simulation.java.
Referenced by cellsociety_team01.modelview.Grid.updateCells().
Member Data Documentation
final String cellsociety_team01.simulations.Simulation.COLORSCHEME_RESOURCE_PACKAGE = "resources/ColorScheme/ColorScheme" static private
Definition at line 18 of file Simulation.java.
ResourceBundle cellsociety_team01.simulations.Simulation.myColorScheme protected
Definition at line 20 of file Simulation.java.
Referenced by cellsociety_team01.simulations.GameOfLife.initialize(), cellsociety_team01.simulations.Segregation.initialize(), cellsociety_team01.simulations.AntForaging.initialize(), cellsociety_team01.simulations.SlimeMolds.initialize(), cellsociety_team01.simulations.SpreadingOfFire.initialize(), cellsociety_team01.simulations.PredatorPrey.initialize(), and cellsociety_team01.simulations.Sugarscape.initialize().
Map<State, ArrayList<Rule> > cellsociety_team01.simulations.Simulation.myData protected
Definition at line 19 of file Simulation.java.
Referenced by cellsociety_team01.simulations.GameOfLife.initialize(), cellsociety_team01.simulations.Segregation.initialize(), cellsociety_team01.simulations.SlimeMolds.initialize(), cellsociety_team01.simulations.AntForaging.initialize(), cellsociety_team01.simulations.SpreadingOfFire.initialize(), cellsociety_team01.simulations.PredatorPrey.initialize(), cellsociety_team01.simulations.Sugarscape.initialize(), cellsociety_team01.simulations.GameOfLife.update(), cellsociety_team01.simulations.SlimeMolds.update(), cellsociety_team01.simulations.Segregation.update(), cellsociety_team01.simulations.SpreadingOfFire.update(), cellsociety_team01.simulations.Sugarscape.update(), cellsociety_team01.simulations.AntForaging.update(), and cellsociety_team01.simulations.PredatorPrey.update().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/simulations/Simulation.java