cellsociety_team01: cellsociety_team01.modelview.RefineNeighborsAlgorithm Class Reference
cellsociety_team01.modelview.RefineNeighborsAlgorithm Class Reference abstract
Public Member Functions
abstract ArrayList< Cell > refineNeighbors (Map< Pair, Cell > cellMap, int rows, int cols, Pair pair, ArrayList< Pair > possibleNeighbors)
Protected Member Functions
Cell findCellForPair (Map< Pair, Cell > cellMap, Pair pair)
Detailed Description
Definition at line 13 of file RefineNeighborsAlgorithm.java.
Member Function Documentation
Cell cellsociety_team01.modelview.RefineNeighborsAlgorithm.findCellForPair (Map< Pair, Cell > cellMap, Pair pair) protected
Finds the cell associated with a pair, necessary because vanilla get() map method uses pointers
Parameters
cellMap
pair
Returns
Definition at line 26 of file RefineNeighborsAlgorithm.java.
References cellsociety_team01.Pair.getX(), and cellsociety_team01.Pair.getY().
Referenced by cellsociety_team01.modelview.FiniteRefineNeighborsAlgorithm.refineNeighbors(), cellsociety_team01.modelview.ToroidalRefineNeighborsAlgorithm.refineNeighbors(), and cellsociety_team01.modelview.InfiniteRefineNeighborsAlgorithm.refineNeighbors().
abstract ArrayList<Cell> cellsociety_team01.modelview.RefineNeighborsAlgorithm.refineNeighbors (Map< Pair, Cell > cellMap, int rows, int cols, Pair pair, ArrayList< Pair > possibleNeighbors) abstract
Referenced by cellsociety_team01.modelview.GridModel.verifyNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/modelview/RefineNeighborsAlgorithm.java