cellsociety_team01: cellsociety_team01.CellState.Cell Class Reference
cellsociety_team01.CellState.Cell Class Reference
Public Member Functions
Cell (int x, int y, State s)
void setUpdated (boolean target)
ArrayList< Cell > getNeighbors ()
boolean isUpdated ()
void setX (int x)
void setY (int y)
int getX ()
int getY ()
State getCurState ()
State getNextState ()
void updateCurState ()
void setCurState (State s)
void setNextState (State s)
Private Attributes
int myX
int myY
ArrayList< Cell > myNeighbors
State myCurState
State myNextState
boolean updated
Detailed Description
Definition at line 6 of file Cell.java.
Constructor & Destructor Documentation
cellsociety_team01.CellState.Cell.Cell (int x, int y, State s)
Definition at line 16 of file Cell.java.
Member Function Documentation
State cellsociety_team01.CellState.Cell.getCurState ()
Definition at line 53 of file Cell.java.
References cellsociety_team01.CellState.Cell.myCurState.
Referenced by cellsociety_team01.rules.averageUpdateRule.apply(), cellsociety_team01.rules.ThresholdMovementRule.apply(), cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.ThresholdStatusRule.apply(), cellsociety_team01.rules.PriorityForwardRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.rules.MovementRule.apply(), cellsociety_team01.rules.ConsumptionRule.apply(), cellsociety_team01.rules.UphillMovementRule.pickCell(), cellsociety_team01.rules.MovementRule.switchStatesUpdated(), cellsociety_team01.simulations.GameOfLife.update(), cellsociety_team01.simulations.SlimeMolds.update(), cellsociety_team01.simulations.Segregation.update(), cellsociety_team01.simulations.SpreadingOfFire.update(), cellsociety_team01.simulations.Sugarscape.update(), cellsociety_team01.simulations.AntForaging.update(), and cellsociety_team01.simulations.PredatorPrey.update().
ArrayList<Cell> cellsociety_team01.CellState.Cell.getNeighbors ()
Definition at line 29 of file Cell.java.
References cellsociety_team01.CellState.Cell.myNeighbors.
State cellsociety_team01.CellState.Cell.getNextState ()
Definition at line 57 of file Cell.java.
References cellsociety_team01.CellState.Cell.myNextState.
Referenced by cellsociety_team01.rules.averageUpdateRule.apply(), cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.StatusRule.apply(), cellsociety_team01.rules.PriorityForwardRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.rules.ConsumptionRule.eat(), and cellsociety_team01.simulations.Sugarscape.update().
int cellsociety_team01.CellState.Cell.getX ()
Definition at line 45 of file Cell.java.
References cellsociety_team01.CellState.Cell.myX.
Referenced by cellsociety_team01.modelview.GridModel.getAllPossibleNeighbors(), cellsociety_team01.modelview.TriangularGridModel.getCardinalNeighbors(), and cellsociety_team01.modelview.SquareGridModel.getCardinalNeighbors().
int cellsociety_team01.CellState.Cell.getY ()
Definition at line 49 of file Cell.java.
References cellsociety_team01.CellState.Cell.myY.
Referenced by cellsociety_team01.modelview.GridModel.getAllPossibleNeighbors(), cellsociety_team01.modelview.TriangularGridModel.getCardinalNeighbors(), and cellsociety_team01.modelview.SquareGridModel.getCardinalNeighbors().
boolean cellsociety_team01.CellState.Cell.isUpdated ()
Definition at line 33 of file Cell.java.
References cellsociety_team01.CellState.Cell.updated.
Referenced by cellsociety_team01.rules.averageUpdateRule.apply(), cellsociety_team01.rules.ThresholdMovementRule.apply(), cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.RandomRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.rules.MovementRule.apply(), cellsociety_team01.simulations.GameOfLife.update(), cellsociety_team01.simulations.Segregation.update(), cellsociety_team01.simulations.SpreadingOfFire.update(), cellsociety_team01.simulations.Sugarscape.update(), cellsociety_team01.simulations.PredatorPrey.update(), and cellsociety_team01.simulations.AntForaging.update().
void cellsociety_team01.CellState.Cell.setCurState (State s)
Definition at line 65 of file Cell.java.
Referenced by cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.PriorityForwardRule.apply(), cellsociety_team01.rules.MovementRule.apply(), cellsociety_team01.rules.ConsumptionRule.eat(), cellsociety_team01.rules.ConsumptionRule.kill(), and cellsociety_team01.rules.MovementRule.switchStatesUpdated().
void cellsociety_team01.CellState.Cell.setNextState (State s)
Definition at line 69 of file Cell.java.
Referenced by cellsociety_team01.rules.averageUpdateRule.apply(), cellsociety_team01.rules.ThresholdMovementRule.apply(), cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.StatusRule.apply(), cellsociety_team01.rules.PriorityForwardRule.apply(), cellsociety_team01.rules.ThresholdRule.apply(), cellsociety_team01.rules.RandomRule.apply(), cellsociety_team01.rules.MovementRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.rules.ConsumptionRule.kill(), cellsociety_team01.rules.MovementRule.switchStatesUpdated(), cellsociety_team01.simulations.GameOfLife.update(), cellsociety_team01.simulations.Segregation.update(), cellsociety_team01.simulations.SpreadingOfFire.update(), cellsociety_team01.simulations.Sugarscape.update(), cellsociety_team01.simulations.PredatorPrey.update(), and cellsociety_team01.simulations.AntForaging.update().
void cellsociety_team01.CellState.Cell.setUpdated (boolean target)
Definition at line 25 of file Cell.java.
Referenced by cellsociety_team01.rules.ThresholdMovementRule.apply(), cellsociety_team01.rules.UphillMovementRule.apply(), cellsociety_team01.rules.RandomRule.apply(), cellsociety_team01.rules.ThresholdRule.apply(), cellsociety_team01.rules.PriorityForwardRule.apply(), cellsociety_team01.rules.ReproductionRule.apply(), cellsociety_team01.rules.MovementRule.apply(), cellsociety_team01.simulations.Simulation.setUpdated(), and cellsociety_team01.rules.MovementRule.switchStatesUpdated().
void cellsociety_team01.CellState.Cell.setX (int x)
Definition at line 37 of file Cell.java.
void cellsociety_team01.CellState.Cell.setY (int y)
Definition at line 41 of file Cell.java.
void cellsociety_team01.CellState.Cell.updateCurState ()
Definition at line 60 of file Cell.java.
References cellsociety_team01.CellState.Cell.myNextState.
Member Data Documentation
State cellsociety_team01.CellState.Cell.myCurState private
Definition at line 12 of file Cell.java.
Referenced by cellsociety_team01.CellState.Cell.getCurState().
ArrayList<Cell> cellsociety_team01.CellState.Cell.myNeighbors private
Definition at line 10 of file Cell.java.
Referenced by cellsociety_team01.CellState.Cell.getNeighbors().
State cellsociety_team01.CellState.Cell.myNextState private
Definition at line 13 of file Cell.java.
Referenced by cellsociety_team01.CellState.Cell.getNextState(), and cellsociety_team01.CellState.Cell.updateCurState().
int cellsociety_team01.CellState.Cell.myX private
Definition at line 8 of file Cell.java.
Referenced by cellsociety_team01.CellState.Cell.getX().
int cellsociety_team01.CellState.Cell.myY private
Definition at line 9 of file Cell.java.
Referenced by cellsociety_team01.CellState.Cell.getY().
boolean cellsociety_team01.CellState.Cell.updated private
Definition at line 14 of file Cell.java.
Referenced by cellsociety_team01.CellState.Cell.isUpdated().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/CellState/Cell.java