cellsociety_team01: cellsociety_team01.parser.Parser Class Reference
cellsociety_team01.parser.Parser Class Reference
Public Member Functions
Parser (File file, Grid grid)
void parseXmlFile ()
Private Member Functions
void parseInfo (Element info)
Simulation makeSim (String textValue)
void parseConfig (Element config)
Map< String, String > getChildValues (Element element)
void parseGrid (Element grid)
void placeGivenCells (Element team)
void placeDistributedCells (Element team)
void placeRandomCells (Element team, boolean last)
void checkLocation (Pair location) throws CellLocationException
void fillMap (String teamName, int population)
void addCell (Pair location, State state)
String getTextValue (Element element, String tagName) throws ElementValueException
State getState (String color)
Private Attributes
ResourceBundle myDefVals
File myFile
Grid myGrid
String myFilename
Element myRoot
Simulation mySim
String myCellPlacement
int myWidth
int myHeight
Map< Pair, Cell > myCells
Random myRandom
int myNullCells
Static Private Attributes
static final String DEFVALS_RESOURCE_PACKAGE = "resources/DefVals/DefVals"
Detailed Description
Definition at line 37 of file Parser.java.
Constructor & Destructor Documentation
cellsociety_team01.parser.Parser.Parser (File file, Grid grid)
Definition at line 54 of file Parser.java.
Member Function Documentation
void cellsociety_team01.parser.Parser.addCell (Pair location, State state) private
Definition at line 258 of file Parser.java.
References cellsociety_team01.Pair.getX(), and cellsociety_team01.Pair.getY().
Referenced by cellsociety_team01.parser.Parser.fillMap(), and cellsociety_team01.parser.Parser.placeGivenCells().
void cellsociety_team01.parser.Parser.checkLocation (Pair location) throws CellLocationException private
Definition at line 237 of file Parser.java.
References cellsociety_team01.parser.Parser.myHeight, and cellsociety_team01.parser.Parser.myWidth.
Referenced by cellsociety_team01.parser.Parser.placeGivenCells().
void cellsociety_team01.parser.Parser.fillMap (String teamName, int population) private
Definition at line 245 of file Parser.java.
References cellsociety_team01.parser.Parser.addCell(), cellsociety_team01.parser.Parser.getState(), cellsociety_team01.Pair.getX(), and cellsociety_team01.Pair.getY().
Referenced by cellsociety_team01.parser.Parser.placeDistributedCells(), and cellsociety_team01.parser.Parser.placeRandomCells().
Map<String, String> cellsociety_team01.parser.Parser.getChildValues (Element element) private
Definition at line 137 of file Parser.java.
References cellsociety_team01.parser.Parser.getTextValue(), and cellsociety_team01.exceptions.ElementValueException.handleException().
Referenced by cellsociety_team01.parser.Parser.parseConfig(), and cellsociety_team01.parser.Parser.parseInfo().
State cellsociety_team01.parser.Parser.getState (String color) private
Definition at line 276 of file Parser.java.
References cellsociety_team01.simulations.Simulation.findState().
Referenced by cellsociety_team01.parser.Parser.fillMap(), and cellsociety_team01.parser.Parser.placeGivenCells().
String cellsociety_team01.parser.Parser.getTextValue (Element element, String tagName) throws ElementValueException private
Definition at line 264 of file Parser.java.
Referenced by cellsociety_team01.parser.Parser.getChildValues(), cellsociety_team01.parser.Parser.placeDistributedCells(), and cellsociety_team01.parser.Parser.placeGivenCells().
Simulation cellsociety_team01.parser.Parser.makeSim (String textValue) private
Definition at line 94 of file Parser.java.
References cellsociety_team01.exceptions.SimulationTypeException.handleException().
Referenced by cellsociety_team01.parser.Parser.parseInfo().
void cellsociety_team01.parser.Parser.parseConfig (Element config) private
Definition at line 120 of file Parser.java.
References cellsociety_team01.parser.Parser.getChildValues(), cellsociety_team01.modelview.Grid.setConfigs(), and cellsociety_team01.simulations.Simulation.setConfigs().
Referenced by cellsociety_team01.parser.Parser.parseXmlFile().
void cellsociety_team01.parser.Parser.parseGrid (Element grid) private
Definition at line 155 of file Parser.java.
References cellsociety_team01.simulations.Simulation.getNumPossibleStates(), cellsociety_team01.exceptions.CellLocationException.handleException(), cellsociety_team01.parser.Parser.myHeight, cellsociety_team01.parser.Parser.placeDistributedCells(), cellsociety_team01.parser.Parser.placeGivenCells(), cellsociety_team01.parser.Parser.placeRandomCells(), cellsociety_team01.modelview.Grid.setBounds(), cellsociety_team01.modelview.Grid.setNeighbors(), and cellsociety_team01.modelview.Grid.updateGrid().
Referenced by cellsociety_team01.parser.Parser.parseXmlFile().
void cellsociety_team01.parser.Parser.parseInfo (Element info) private
Definition at line 85 of file Parser.java.
References cellsociety_team01.parser.Parser.getChildValues(), cellsociety_team01.parser.Parser.makeSim(), cellsociety_team01.modelview.Grid.setAuthor(), cellsociety_team01.modelview.Grid.setSimulation(), and cellsociety_team01.modelview.Grid.setTitle().
Referenced by cellsociety_team01.parser.Parser.parseXmlFile().
void cellsociety_team01.parser.Parser.parseXmlFile ()
Definition at line 61 of file Parser.java.
References cellsociety_team01.parser.Parser.parseConfig(), cellsociety_team01.parser.Parser.parseGrid(), and cellsociety_team01.parser.Parser.parseInfo().
Referenced by cellsociety_team01.modelview.GUI.loadXML(), and cellsociety_team01.modelview.GUI.reset().
void cellsociety_team01.parser.Parser.placeDistributedCells (Element team) private
Definition at line 213 of file Parser.java.
References cellsociety_team01.parser.Parser.fillMap(), cellsociety_team01.parser.Parser.getTextValue(), and cellsociety_team01.exceptions.ElementValueException.handleException().
Referenced by cellsociety_team01.parser.Parser.parseGrid().
void cellsociety_team01.parser.Parser.placeGivenCells (Element team) private
Definition at line 191 of file Parser.java.
References cellsociety_team01.parser.Parser.addCell(), cellsociety_team01.parser.Parser.checkLocation(), cellsociety_team01.parser.Parser.getState(), cellsociety_team01.parser.Parser.getTextValue(), cellsociety_team01.exceptions.CellLocationException.handleException(), and cellsociety_team01.exceptions.ElementValueException.handleException().
Referenced by cellsociety_team01.parser.Parser.parseGrid().
void cellsociety_team01.parser.Parser.placeRandomCells (Element team, boolean last) private
Definition at line 226 of file Parser.java.
References cellsociety_team01.parser.Parser.fillMap(), and cellsociety_team01.parser.Parser.myNullCells.
Referenced by cellsociety_team01.parser.Parser.parseGrid().
Member Data Documentation
final String cellsociety_team01.parser.Parser.DEFVALS_RESOURCE_PACKAGE = "resources/DefVals/DefVals" static private
Definition at line 39 of file Parser.java.
String cellsociety_team01.parser.Parser.myCellPlacement private
Definition at line 47 of file Parser.java.
Map<Pair, Cell> cellsociety_team01.parser.Parser.myCells private
Definition at line 50 of file Parser.java.
ResourceBundle cellsociety_team01.parser.Parser.myDefVals private
Definition at line 40 of file Parser.java.
File cellsociety_team01.parser.Parser.myFile private
Definition at line 42 of file Parser.java.
String cellsociety_team01.parser.Parser.myFilename private
Definition at line 44 of file Parser.java.
Grid cellsociety_team01.parser.Parser.myGrid private
Definition at line 43 of file Parser.java.
int cellsociety_team01.parser.Parser.myHeight private
Definition at line 49 of file Parser.java.
Referenced by cellsociety_team01.parser.Parser.checkLocation(), and cellsociety_team01.parser.Parser.parseGrid().
int cellsociety_team01.parser.Parser.myNullCells private
Definition at line 52 of file Parser.java.
Referenced by cellsociety_team01.parser.Parser.placeRandomCells().
Random cellsociety_team01.parser.Parser.myRandom private
Definition at line 51 of file Parser.java.
Element cellsociety_team01.parser.Parser.myRoot private
Definition at line 45 of file Parser.java.
Simulation cellsociety_team01.parser.Parser.mySim private
Definition at line 46 of file Parser.java.
int cellsociety_team01.parser.Parser.myWidth private
Definition at line 48 of file Parser.java.
Referenced by cellsociety_team01.parser.Parser.checkLocation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/parser/Parser.java