cellsociety_team01: cellsociety_team01.CellState.IntState Class Reference
cellsociety_team01.CellState.IntState Class Reference
Public Member Functions
IntState (Color c, String s, int i)
State newInstanceOf ()
void initialize ()
boolean equals (State s)
int hashCode ()
int getNumVars ()
int[] getStateNums ()
int getInt (int i)
void setInt (int target, int value)
Public Member Functions inherited from cellsociety_team01.CellState.State
State (Color c, String s)
State newInstanceOf ()
boolean equals (Object s)
int hashCode ()
void setColor (Color color)
void setName (String s)
String getName ()
Color getColor ()
int getInt (int a)
int getNumArgs ()
void setInt (int a, int b)
boolean comparePopulations (State curState)
String getDemonym ()
void updateColor ()
boolean getFunc ()
Protected Attributes
int[] stateNums
Protected Attributes inherited from cellsociety_team01.CellState.State
Color myColor
String myName
Detailed Description
Definition at line 4 of file IntState.java.
Constructor & Destructor Documentation
cellsociety_team01.CellState.IntState.IntState (Color c, String s, int i)
Definition at line 8 of file IntState.java.
References cellsociety_team01.CellState.IntState.initialize().
Referenced by cellsociety_team01.CellState.IntState.newInstanceOf().
Member Function Documentation
boolean cellsociety_team01.CellState.IntState.equals (State s)
Definition at line 24 of file IntState.java.
int cellsociety_team01.CellState.IntState.getInt (int i)
Definition at line 40 of file IntState.java.
int cellsociety_team01.CellState.IntState.getNumVars ()
Definition at line 32 of file IntState.java.
int [] cellsociety_team01.CellState.IntState.getStateNums ()
Definition at line 36 of file IntState.java.
References cellsociety_team01.CellState.IntState.stateNums.
int cellsociety_team01.CellState.IntState.hashCode ()
Definition at line 28 of file IntState.java.
void cellsociety_team01.CellState.IntState.initialize ()
Definition at line 18 of file IntState.java.
Referenced by cellsociety_team01.CellState.DirectionalAutomaton.DirectionalAutomaton(), and cellsociety_team01.CellState.IntState.IntState().
State cellsociety_team01.CellState.IntState.newInstanceOf ()
Definition at line 14 of file IntState.java.
References cellsociety_team01.CellState.IntState.IntState(), cellsociety_team01.CellState.State.myColor, and cellsociety_team01.CellState.State.myName.
void cellsociety_team01.CellState.IntState.setInt (int target, int value)
Definition at line 44 of file IntState.java.
Referenced by cellsociety_team01.CellState.ColorChangeIntState.newInstanceOf().
Member Data Documentation
int [] cellsociety_team01.CellState.IntState.stateNums protected
Definition at line 6 of file IntState.java.
Referenced by cellsociety_team01.CellState.IntState.getStateNums(), cellsociety_team01.CellState.ColorChangeIntState.newInstanceOf(), and cellsociety_team01.CellState.ColorChangeIntState.updateColor().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/CellState/IntState.java