cellsociety_team01: cellsociety_team01.simulations.AntForaging Class Reference
cellsociety_team01.simulations.AntForaging Class Reference
Public Member Functions
AntForaging ()
void initialize ()
int getNeighborType ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
void parseConfigs (Map< String, String > configs)
Public Member Functions inherited from cellsociety_team01.simulations.Simulation
Simulation ()
int getNumPossibleStates ()
int getNeighborType ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
void setUpdated (Cell c)
State findState (String identifier)
Set< State > getStates ()
void setConfigs (Map< String, String > a)
void initialize ()
void parseConfigs (Map< String, String > a)
State cycleNextState (State s)
Private Attributes
int myMaxPheremoneLevel
Additional Inherited Members
Protected Attributes inherited from cellsociety_team01.simulations.Simulation
Map< State, ArrayList< Rule > > myData
ResourceBundle myColorScheme
Detailed Description
Definition at line 15 of file AntForaging.java.
Constructor & Destructor Documentation
cellsociety_team01.simulations.AntForaging.AntForaging ()
Definition at line 19 of file AntForaging.java.
Member Function Documentation
int cellsociety_team01.simulations.AntForaging.getNeighborType ()
Definition at line 50 of file AntForaging.java.
void cellsociety_team01.simulations.AntForaging.initialize ()
Definition at line 23 of file AntForaging.java.
References cellsociety_team01.simulations.Simulation.myColorScheme, cellsociety_team01.simulations.Simulation.myData, and cellsociety_team01.CellState.State.setInt().
void cellsociety_team01.simulations.AntForaging.parseConfigs (Map< String, String > configs)
Definition at line 62 of file AntForaging.java.
void cellsociety_team01.simulations.AntForaging.update (Cell cur, ArrayList< Cell > myNeighbors)
Definition at line 52 of file AntForaging.java.
References cellsociety_team01.CellState.Cell.getCurState(), cellsociety_team01.CellState.Cell.isUpdated(), cellsociety_team01.simulations.Simulation.myData, and cellsociety_team01.CellState.Cell.setNextState().
Member Data Documentation
int cellsociety_team01.simulations.AntForaging.myMaxPheremoneLevel private
Definition at line 17 of file AntForaging.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/simulations/AntForaging.java