cellsociety_team01: cellsociety_team01.rules.RandomRule Class Reference
cellsociety_team01.rules.RandomRule Class Reference
Public Member Functions
RandomRule (State start, State end, State cause, double prob)
void apply (Cell cur, ArrayList< Cell > myNeighbors)
boolean applies (int k)
Public Member Functions inherited from cellsociety_team01.rules.ChangingRule
ChangingRule (State start, State end)
State getStart ()
State getEnd ()
boolean applies (int k)
Public Member Functions inherited from cellsociety_team01.rules.Rule
Rule ()
void update ()
void apply (Cell cur, ArrayList< Cell > myNeighbors)
Protected Attributes
State myCause
Protected Attributes inherited from cellsociety_team01.rules.ChangingRule
State myStart
State myEnd
Package Attributes
Random myGen = new Random()
Private Attributes
double myProb
Detailed Description
Definition at line 9 of file RandomRule.java.
Constructor & Destructor Documentation
cellsociety_team01.rules.RandomRule.RandomRule (State start, State end, State cause, double prob)
Definition at line 15 of file RandomRule.java.
Member Function Documentation
boolean cellsociety_team01.rules.RandomRule.applies (int k)
Definition at line 36 of file RandomRule.java.
References cellsociety_team01.rules.RandomRule.myProb.
Referenced by cellsociety_team01.rules.RandomRule.apply().
void cellsociety_team01.rules.RandomRule.apply (Cell cur, ArrayList< Cell > myNeighbors)
Definition at line 21 of file RandomRule.java.
References cellsociety_team01.rules.RandomRule.applies(), cellsociety_team01.CellState.Cell.isUpdated(), cellsociety_team01.rules.ChangingRule.myEnd, cellsociety_team01.CellState.Cell.setNextState(), and cellsociety_team01.CellState.Cell.setUpdated().
Member Data Documentation
State cellsociety_team01.rules.RandomRule.myCause protected
Definition at line 13 of file RandomRule.java.
Random cellsociety_team01.rules.RandomRule.myGen = new Random() package
Definition at line 12 of file RandomRule.java.
double cellsociety_team01.rules.RandomRule.myProb private
Definition at line 11 of file RandomRule.java.
Referenced by cellsociety_team01.rules.RandomRule.applies().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/rules/RandomRule.java