cellsociety_team01: cellsociety_team01.CellState.Race Class Reference
cellsociety_team01.CellState.Race Class Reference
Public Member Functions
Race (Color c, String demonym)
String getDemonym ()
boolean comparePopulations (State s)
Public Member Functions inherited from cellsociety_team01.CellState.State
State (Color c, String s)
State newInstanceOf ()
boolean equals (Object s)
int hashCode ()
void setColor (Color color)
void setName (String s)
String getName ()
Color getColor ()
int getInt (int a)
int getNumArgs ()
void setInt (int a, int b)
boolean comparePopulations (State curState)
String getDemonym ()
void updateColor ()
boolean getFunc ()
Protected Attributes
String myDemonym
Protected Attributes inherited from cellsociety_team01.CellState.State
Color myColor
String myName
Detailed Description
Definition at line 5 of file Race.java.
Constructor & Destructor Documentation
cellsociety_team01.CellState.Race.Race (Color c, String demonym)
Definition at line 9 of file Race.java.
Referenced by cellsociety_team01.CellState.Race.comparePopulations().
Member Function Documentation
boolean cellsociety_team01.CellState.Race.comparePopulations (State s)
Definition at line 18 of file Race.java.
References cellsociety_team01.CellState.Race.getDemonym(), and cellsociety_team01.CellState.Race.Race().
String cellsociety_team01.CellState.Race.getDemonym ()
Definition at line 14 of file Race.java.
References cellsociety_team01.CellState.Race.myDemonym.
Referenced by cellsociety_team01.CellState.Race.comparePopulations().
Member Data Documentation
String cellsociety_team01.CellState.Race.myDemonym protected
Definition at line 7 of file Race.java.
Referenced by cellsociety_team01.CellState.Race.getDemonym().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/CellState/Race.java