cellsociety_team01: cellsociety_team01.modelview.Grid Class Reference
cellsociety_team01.modelview.Grid Class Reference
Classes
enum gridEdgeTypes
enum gridShapeTypes
Public Member Functions
Grid ()
void setConfigs (Map< String, String > configs)
void setView (GUI viewIn)
void setBounds (Pair bounds)
void setAnimationLoop (Timeline anIn)
void setSimulation (Simulation simulationIn)
void setAuthor (String authorIn)
void setTitle (String titleIn)
void setNeighbors (Map< Pair, Cell > cellMap)
void updateGrid (Collection< Cell > cellsIn)
KeyFrame start (double frameRate)
void changeUpdateRate (double newRate)
void play ()
void pause ()
void step ()
void update ()
void updateCurStates ()
void cycleCellState (int cellX, int cellY)
boolean isGridOutlined ()
boolean isSimRunning ()
int getRows ()
int getCols ()
ArrayList< Cell > getCells ()
gridShapeTypes getShape ()
String getAuthor ()
Series fillGraphSeries (Series series, int tick)
Package Attributes
Simulation simulation
int cols
int rows
Private Member Functions
void updateCells ()
void setNotUpdated ()
Private Attributes
ArrayList< Cell > cells
GUI myView
boolean simRunning
double updateRate
Timeline myLoop
String author
GridModel myGridModel
gridShapeTypes myCellShape
gridEdgeTypes myEdgeType
boolean gridOutline
Detailed Description
Definition at line 20 of file Grid.java.
Constructor & Destructor Documentation
cellsociety_team01.modelview.Grid.Grid ()
Definition at line 43 of file Grid.java.
Member Function Documentation
void cellsociety_team01.modelview.Grid.changeUpdateRate (double newRate)
Changes the sim refresh rate
Parameters
newRate
Definition at line 171 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.update().
void cellsociety_team01.modelview.Grid.cycleCellState (int cellX, int cellY)
Cycles the state of a given cell
Parameters
cellX
cellY
Definition at line 253 of file Grid.java.
References cellsociety_team01.simulations.Simulation.cycleNextState(), and cellsociety_team01.modelview.GUI.update().
Referenced by cellsociety_team01.modelview.GUI.cellClicked().
Series cellsociety_team01.modelview.Grid.fillGraphSeries (Series series, int tick)
Fills a series with data on State population, CURRENTLY UNIMPLEMENTED
Parameters
series
tick
Returns
Definition at line 332 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.makeGraph().
String cellsociety_team01.modelview.Grid.getAuthor ()
gets the author
Returns
Definition at line 321 of file Grid.java.
ArrayList<Cell> cellsociety_team01.modelview.Grid.getCells ()
Returns cells
Returns
Definition at line 303 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.setGridCellStates().
int cellsociety_team01.modelview.Grid.getCols ()
gets number of cols
Returns
Definition at line 294 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.GUI(), and cellsociety_team01.modelview.GUI.loadXML().
int cellsociety_team01.modelview.Grid.getRows ()
Gets number of rows
Returns
Definition at line 285 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.GUI(), and cellsociety_team01.modelview.GUI.loadXML().
gridShapeTypes cellsociety_team01.modelview.Grid.getShape ()
Returns which shape the cells are
Returns
Definition at line 312 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.makeGrid().
boolean cellsociety_team01.modelview.Grid.isGridOutlined ()
check is the XML file said to outline the grid cells
Returns
Definition at line 267 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.makeGrid().
boolean cellsociety_team01.modelview.Grid.isSimRunning ()
Checks if the simulation is running
Returns
Definition at line 276 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.enableButtons(), and cellsociety_team01.modelview.GUI.update().
void cellsociety_team01.modelview.Grid.pause ()
Handles pressing of the pause button
Definition at line 191 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.makeButtonsAndSlider().
void cellsociety_team01.modelview.Grid.play ()
Handles pressing of the play button
Definition at line 184 of file Grid.java.
Referenced by cellsociety_team01.modelview.GUI.makeButtonsAndSlider(), and cellsociety_team01.modelview.GUI.makePrefPanel().
void cellsociety_team01.modelview.Grid.setAnimationLoop (Timeline anIn)
Sets the animation loop, used during initialization
Parameters
anIn
Definition at line 108 of file Grid.java.
Referenced by cellsociety_team01.Main.start().
void cellsociety_team01.modelview.Grid.setAuthor (String authorIn)
Sets the author, provided by the XML file
Parameters
authorIn
Definition at line 126 of file Grid.java.
Referenced by cellsociety_team01.parser.Parser.parseInfo().
void cellsociety_team01.modelview.Grid.setBounds (Pair bounds)
Called by parser to set rows and cols
Parameters
bounds
Definition at line 98 of file Grid.java.
References cellsociety_team01.Pair.getX(), and cellsociety_team01.Pair.getY().
Referenced by cellsociety_team01.parser.Parser.parseGrid().
void cellsociety_team01.modelview.Grid.setConfigs (Map< String, String > configs)
Called by Parser to set up the grid / cells
Parameters
configs
Definition at line 52 of file Grid.java.
References cellsociety_team01.modelview.Grid.gridEdgeTypes.FINITE, cellsociety_team01.exceptions.BadGridConfigException.handleException(), cellsociety_team01.modelview.Grid.gridEdgeTypes.INFINITE, and cellsociety_team01.modelview.Grid.gridEdgeTypes.TOROIDAL.
Referenced by cellsociety_team01.parser.Parser.parseConfig().
void cellsociety_team01.modelview.Grid.setNeighbors (Map< Pair, Cell > cellMap)
Called during initialization to set which cells are neighbors
Parameters
cellMap
Definition at line 144 of file Grid.java.
References cellsociety_team01.modelview.GridModel.setNeighbors().
Referenced by cellsociety_team01.parser.Parser.parseGrid().
void cellsociety_team01.modelview.Grid.setNotUpdated () private
Sets each cell to be not updated, used to prevent cells moving during an update sweep
Definition at line 233 of file Grid.java.
void cellsociety_team01.modelview.Grid.setSimulation (Simulation simulationIn)
Sets which simulation to use
Parameters
simulationIn
Definition at line 117 of file Grid.java.
Referenced by cellsociety_team01.parser.Parser.parseInfo().
void cellsociety_team01.modelview.Grid.setTitle (String titleIn)
Sets the title of the simulation
Parameters
titleIn
Definition at line 135 of file Grid.java.
References cellsociety_team01.modelview.GUI.getStage().
Referenced by cellsociety_team01.parser.Parser.parseInfo().
void cellsociety_team01.modelview.Grid.setView (GUI viewIn)
Sets this models view controller
Parameters
viewIn
Definition at line 89 of file Grid.java.
Referenced by cellsociety_team01.Main.start().
KeyFrame cellsociety_team01.modelview.Grid.start (double frameRate)
Creates the game's frame
Definition at line 161 of file Grid.java.
Referenced by cellsociety_team01.Main.start().
void cellsociety_team01.modelview.Grid.step ()
Handles pressing of the step button
Definition at line 198 of file Grid.java.
References cellsociety_team01.modelview.GUI.update().
Referenced by cellsociety_team01.modelview.GUI.makeButtonsAndSlider().
void cellsociety_team01.modelview.Grid.update ()
Main update method
Definition at line 207 of file Grid.java.
References cellsociety_team01.modelview.GUI.update().
void cellsociety_team01.modelview.Grid.updateCells () private
Tells each cell to determine its next state
Definition at line 218 of file Grid.java.
References cellsociety_team01.simulations.Simulation.getStates(), and cellsociety_team01.simulations.Simulation.update().
void cellsociety_team01.modelview.Grid.updateCurStates ()
Tells each cell to update their current states
Definition at line 242 of file Grid.java.
void cellsociety_team01.modelview.Grid.updateGrid (Collection< Cell > cellsIn)
updates the Grid with a new collection of cells
Parameters
cellsIn
Definition at line 153 of file Grid.java.
Referenced by cellsociety_team01.parser.Parser.parseGrid().
Member Data Documentation
String cellsociety_team01.modelview.Grid.author private
Definition at line 36 of file Grid.java.
ArrayList<Cell> cellsociety_team01.modelview.Grid.cells private
Definition at line 31 of file Grid.java.
int cellsociety_team01.modelview.Grid.cols package
Definition at line 37 of file Grid.java.
boolean cellsociety_team01.modelview.Grid.gridOutline private
Definition at line 41 of file Grid.java.
gridShapeTypes cellsociety_team01.modelview.Grid.myCellShape private
Definition at line 39 of file Grid.java.
gridEdgeTypes cellsociety_team01.modelview.Grid.myEdgeType private
Definition at line 40 of file Grid.java.
GridModel cellsociety_team01.modelview.Grid.myGridModel private
Definition at line 38 of file Grid.java.
Timeline cellsociety_team01.modelview.Grid.myLoop private
Definition at line 35 of file Grid.java.
GUI cellsociety_team01.modelview.Grid.myView private
Definition at line 32 of file Grid.java.
int cellsociety_team01.modelview.Grid.rows package
Definition at line 37 of file Grid.java.
boolean cellsociety_team01.modelview.Grid.simRunning private
Definition at line 33 of file Grid.java.
Simulation cellsociety_team01.modelview.Grid.simulation package
Definition at line 28 of file Grid.java.
double cellsociety_team01.modelview.Grid.updateRate private
Definition at line 34 of file Grid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/modelview/Grid.java