cellsociety_team01: cellsociety_team01.simulations.Sugarscape Class Reference
cellsociety_team01.simulations.Sugarscape Class Reference
Public Member Functions
Sugarscape ()
int getNeighborType ()
void initialize ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
void parseConfigs (Map< String, String > configs)
Public Member Functions inherited from cellsociety_team01.simulations.Simulation
Simulation ()
int getNumPossibleStates ()
int getNeighborType ()
void update (Cell cur, ArrayList< Cell > myNeighbors)
void setUpdated (Cell c)
State findState (String identifier)
Set< State > getStates ()
void setConfigs (Map< String, String > a)
void initialize ()
void parseConfigs (Map< String, String > a)
State cycleNextState (State s)
Public Attributes
int MAX_VISION
int MAX_SUGAR
Additional Inherited Members
Protected Attributes inherited from cellsociety_team01.simulations.Simulation
Map< State, ArrayList< Rule > > myData
ResourceBundle myColorScheme
Detailed Description
Definition at line 17 of file Sugarscape.java.
Constructor & Destructor Documentation
cellsociety_team01.simulations.Sugarscape.Sugarscape ()
Definition at line 22 of file Sugarscape.java.
Member Function Documentation
int cellsociety_team01.simulations.Sugarscape.getNeighborType ()
Definition at line 26 of file Sugarscape.java.
References cellsociety_team01.simulations.Sugarscape.MAX_VISION.
void cellsociety_team01.simulations.Sugarscape.initialize ()
Definition at line 30 of file Sugarscape.java.
References cellsociety_team01.simulations.Simulation.myColorScheme, and cellsociety_team01.simulations.Simulation.myData.
void cellsociety_team01.simulations.Sugarscape.parseConfigs (Map< String, String > configs)
Definition at line 66 of file Sugarscape.java.
void cellsociety_team01.simulations.Sugarscape.update (Cell cur, ArrayList< Cell > myNeighbors)
Definition at line 52 of file Sugarscape.java.
References cellsociety_team01.CellState.Cell.getCurState(), cellsociety_team01.CellState.Cell.getNextState(), cellsociety_team01.CellState.Cell.isUpdated(), cellsociety_team01.simulations.Simulation.myData, cellsociety_team01.CellState.Cell.setNextState(), and cellsociety_team01.CellState.State.updateColor().
Member Data Documentation
int cellsociety_team01.simulations.Sugarscape.MAX_SUGAR
Definition at line 20 of file Sugarscape.java.
int cellsociety_team01.simulations.Sugarscape.MAX_VISION
Definition at line 19 of file Sugarscape.java.
Referenced by cellsociety_team01.simulations.Sugarscape.getNeighborType().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/simulations/Sugarscape.java