cellsociety_team01: cellsociety_team01.modelview.GUI Class Reference
cellsociety_team01.modelview.GUI Class Reference
Public Member Functions
GUI (Grid gridIn, String language, Stage stageIn)
void update (boolean step)
void reset ()
Scene getScene ()
Stage getStage ()
Static Public Attributes
static final Dimension DEFAULT_SIZE = new Dimension(1450, 800)
static final String DEFAULT_RESOURCE_PACKAGE = "resources/"
Private Member Functions
Node makeButtonsAndSlider ()
Button makeButton (String property, EventHandler< ActionEvent > handler)
Node makeSlider ()
Node makeMenuBar ()
Node makeGrid ()
void loadXML ()
void setGridCellStates ()
void cellClicked (MouseEvent e)
void enableButtons ()
Node makeGraph ()
Node makePrefPanel ()
Private Attributes
ResourceBundle myResources
Scene myScene
Grid myModel
Stage myStage
BorderPane myRoot
Button playButton
Button pauseButton
Button stepButton
Button resetButton
Slider slider
TextField textField1
TextField textField2
TextField textField3
Canvas gridCanvas
GridView gridView
Parser parser
File file
int myWidth
int myHeight
int rows
int cols
int tick
Detailed Description
Definition at line 33 of file GUI.java.
Constructor & Destructor Documentation
cellsociety_team01.modelview.GUI.GUI (Grid gridIn, String language, Stage stageIn)
Definition at line 66 of file GUI.java.
References cellsociety_team01.modelview.GUI.enableButtons(), cellsociety_team01.modelview.Grid.getCols(), cellsociety_team01.modelview.Grid.getRows(), cellsociety_team01.modelview.GUI.makeButtonsAndSlider(), and cellsociety_team01.modelview.GUI.makeMenuBar().
Member Function Documentation
void cellsociety_team01.modelview.GUI.cellClicked (MouseEvent e) private
Helper method that handles the user clicking a cell
Parameters
e
Definition at line 230 of file GUI.java.
References cellsociety_team01.modelview.GUI.cols, cellsociety_team01.modelview.Grid.cycleCellState(), and cellsociety_team01.modelview.GUI.rows.
Referenced by cellsociety_team01.modelview.GUI.makeGrid().
void cellsociety_team01.modelview.GUI.enableButtons () private
enables / disables buttons on update
Definition at line 251 of file GUI.java.
References cellsociety_team01.modelview.Grid.isSimRunning().
Referenced by cellsociety_team01.modelview.GUI.GUI(), and cellsociety_team01.modelview.GUI.update().
Scene cellsociety_team01.modelview.GUI.getScene ()
Returns scene for this view so it can be added to stage.
Definition at line 261 of file GUI.java.
References cellsociety_team01.modelview.GUI.myScene.
Referenced by cellsociety_team01.Main.start().
Stage cellsociety_team01.modelview.GUI.getStage ()
Gets stage
Returns
Definition at line 270 of file GUI.java.
References cellsociety_team01.modelview.GUI.myStage.
Referenced by cellsociety_team01.modelview.Grid.setTitle().
void cellsociety_team01.modelview.GUI.loadXML () private
Brings up a file chooser to select an XML file
Definition at line 185 of file GUI.java.
References cellsociety_team01.modelview.Grid.getCols(), cellsociety_team01.modelview.Grid.getRows(), cellsociety_team01.modelview.GUI.makeGrid(), cellsociety_team01.parser.Parser.parseXmlFile(), and cellsociety_team01.modelview.GUI.setGridCellStates().
Referenced by cellsociety_team01.modelview.GUI.makeMenuBar().
Button cellsociety_team01.modelview.GUI.makeButton (String property, EventHandler< ActionEvent > handler) private
Helper method to create buttons with labels and handlers (Taken from the example_browser)
Parameters
property
handler
Returns
Definition at line 120 of file GUI.java.
Referenced by cellsociety_team01.modelview.GUI.makeButtonsAndSlider(), and cellsociety_team01.modelview.GUI.makePrefPanel().
Node cellsociety_team01.modelview.GUI.makeButtonsAndSlider () private
Makes the Buttons and Slider
Returns
Definition at line 94 of file GUI.java.
References cellsociety_team01.modelview.GUI.makeButton(), cellsociety_team01.modelview.GUI.makeSlider(), cellsociety_team01.modelview.Grid.pause(), cellsociety_team01.modelview.Grid.play(), cellsociety_team01.modelview.GUI.reset(), and cellsociety_team01.modelview.Grid.step().
Referenced by cellsociety_team01.modelview.GUI.GUI().
Node cellsociety_team01.modelview.GUI.makeGraph () private
Sets up the graph
Returns
Definition at line 279 of file GUI.java.
References cellsociety_team01.modelview.Grid.fillGraphSeries().
Node cellsociety_team01.modelview.GUI.makeGrid () private
Configures the grid view
Returns
Definition at line 168 of file GUI.java.
References cellsociety_team01.modelview.GUI.cellClicked(), cellsociety_team01.modelview.Grid.getShape(), cellsociety_team01.modelview.GUI.gridCanvas, cellsociety_team01.modelview.Grid.isGridOutlined(), cellsociety_team01.modelview.GridView.makeGrid(), cellsociety_team01.modelview.Grid.gridShapeTypes.SQUARE, and cellsociety_team01.modelview.Grid.gridShapeTypes.TRIANGULAR.
Referenced by cellsociety_team01.modelview.GUI.loadXML().
Node cellsociety_team01.modelview.GUI.makeMenuBar () private
Configures the top menu bar
Returns
Definition at line 150 of file GUI.java.
References cellsociety_team01.modelview.GUI.loadXML().
Referenced by cellsociety_team01.modelview.GUI.GUI().
Node cellsociety_team01.modelview.GUI.makePrefPanel () private
Sets up the preferences panel for changing parameters
Returns
Definition at line 308 of file GUI.java.
References cellsociety_team01.modelview.GUI.makeButton(), and cellsociety_team01.modelview.Grid.play().
Node cellsociety_team01.modelview.GUI.makeSlider () private
Makes the Slider which controls the speed of the simulation
Returns
Definition at line 133 of file GUI.java.
References cellsociety_team01.modelview.GUI.slider.
Referenced by cellsociety_team01.modelview.GUI.makeButtonsAndSlider().
void cellsociety_team01.modelview.GUI.reset ()
Resets the simulation to the last xml file
Definition at line 242 of file GUI.java.
References cellsociety_team01.parser.Parser.parseXmlFile(), and cellsociety_team01.modelview.GUI.setGridCellStates().
Referenced by cellsociety_team01.modelview.GUI.makeButtonsAndSlider().
void cellsociety_team01.modelview.GUI.setGridCellStates () private
Sets grid states based on the cell map in myModel
Definition at line 220 of file GUI.java.
References cellsociety_team01.modelview.Grid.getCells(), and cellsociety_team01.modelview.GridView.setGridCellStates().
Referenced by cellsociety_team01.modelview.GUI.loadXML(), cellsociety_team01.modelview.GUI.reset(), and cellsociety_team01.modelview.GUI.update().
void cellsociety_team01.modelview.GUI.update (boolean step)
updates the GUI, called by grid on update tick
Definition at line 209 of file GUI.java.
References cellsociety_team01.modelview.Grid.changeUpdateRate(), cellsociety_team01.modelview.GUI.enableButtons(), cellsociety_team01.modelview.Grid.isSimRunning(), and cellsociety_team01.modelview.GUI.setGridCellStates().
Referenced by cellsociety_team01.modelview.Grid.cycleCellState(), cellsociety_team01.modelview.Grid.step(), and cellsociety_team01.modelview.Grid.update().
Member Data Documentation
int cellsociety_team01.modelview.GUI.cols private
Definition at line 63 of file GUI.java.
Referenced by cellsociety_team01.modelview.GUI.cellClicked().
final String cellsociety_team01.modelview.GUI.DEFAULT_RESOURCE_PACKAGE = "resources/" static
Definition at line 35 of file GUI.java.
final Dimension cellsociety_team01.modelview.GUI.DEFAULT_SIZE = new Dimension(1450, 800) static
Definition at line 34 of file GUI.java.
File cellsociety_team01.modelview.GUI.file private
Definition at line 58 of file GUI.java.
Canvas cellsociety_team01.modelview.GUI.gridCanvas private
Definition at line 54 of file GUI.java.
Referenced by cellsociety_team01.modelview.GUI.makeGrid().
GridView cellsociety_team01.modelview.GUI.gridView private
Definition at line 55 of file GUI.java.
int cellsociety_team01.modelview.GUI.myHeight private
Definition at line 61 of file GUI.java.
Grid cellsociety_team01.modelview.GUI.myModel private
Definition at line 39 of file GUI.java.
ResourceBundle cellsociety_team01.modelview.GUI.myResources private
Definition at line 37 of file GUI.java.
BorderPane cellsociety_team01.modelview.GUI.myRoot private
Definition at line 41 of file GUI.java.
Scene cellsociety_team01.modelview.GUI.myScene private
Definition at line 38 of file GUI.java.
Referenced by cellsociety_team01.modelview.GUI.getScene().
Stage cellsociety_team01.modelview.GUI.myStage private
Definition at line 40 of file GUI.java.
Referenced by cellsociety_team01.modelview.GUI.getStage().
int cellsociety_team01.modelview.GUI.myWidth private
Definition at line 60 of file GUI.java.
Parser cellsociety_team01.modelview.GUI.parser private
Definition at line 57 of file GUI.java.
Button cellsociety_team01.modelview.GUI.pauseButton private
Definition at line 45 of file GUI.java.
Button cellsociety_team01.modelview.GUI.playButton private
Definition at line 44 of file GUI.java.
Button cellsociety_team01.modelview.GUI.resetButton private
Definition at line 47 of file GUI.java.
int cellsociety_team01.modelview.GUI.rows private
Definition at line 62 of file GUI.java.
Referenced by cellsociety_team01.modelview.GUI.cellClicked().
Slider cellsociety_team01.modelview.GUI.slider private
Definition at line 48 of file GUI.java.
Referenced by cellsociety_team01.modelview.GUI.makeSlider().
Button cellsociety_team01.modelview.GUI.stepButton private
Definition at line 46 of file GUI.java.
TextField cellsociety_team01.modelview.GUI.textField1 private
Definition at line 49 of file GUI.java.
TextField cellsociety_team01.modelview.GUI.textField2 private
Definition at line 50 of file GUI.java.
TextField cellsociety_team01.modelview.GUI.textField3 private
Definition at line 51 of file GUI.java.
int cellsociety_team01.modelview.GUI.tick private
Definition at line 64 of file GUI.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team01/repository/src/cellsociety_team01/modelview/GUI.java